import PDFDocument from 'pdfkit';
import logger from '../utils/logger.js';

// --- Constants & Styles ---
const COLORS = {
    primary: '#2c3e50',    // Dark Blue/Grey for heavy text
    accent: '#3498db',     // Blue for highlights/headers
    text: '#444444',       // Main text color
    grayLight: '#f4f6f7',  // Zebra stripe color
    border: '#e0e0e0'      // Line color
};

const FONTS = {
    bold: 'Helvetica-Bold',
    regular: 'Helvetica',
    italic: 'Helvetica-Oblique'
};

// --- Helper Functions ---

const formatCurrency = (amount, currency) => {
    const num = new Intl.NumberFormat('en-US', {
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
    }).format(amount);
    return `${currency} ${num}`;
};

const drawHeader = (doc, user, title, period) => {
    // Business Name
    doc.fillColor(COLORS.primary)
       .fontSize(20)
       .font(FONTS.bold)
       .text(user.businessName, 50, 45, { align: 'left' })
       
    // Report Title Background
    const pageWidth = doc.page.width;
    doc.rect(pageWidth - 250, 35, 200, 25).fill(COLORS.grayLight);
    
    // Report Title Text
    doc.fillColor(COLORS.text)
       .fontSize(12)
       .font(FONTS.bold)
       .text(title.toUpperCase(), pageWidth - 250, 42, { width: 200, align: 'center' });

    // Date/Period
    if (period) {
        doc.fontSize(10)
           .font(FONTS.regular)
           .text(period, pageWidth - 250, 65, { width: 200, align: 'center' });
    }

    // Divider Line
    doc.strokeColor(COLORS.accent)
       .lineWidth(2)
       .moveTo(50, 90)
       .lineTo(550, 90)
       .stroke();
       
    doc.moveDown(2);
    return doc.y + 20; // Return starting Y for table
};

const drawFooter = (doc) => {
    const pages = doc.bufferedPageRange();
    for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        // Footer Line
        doc.strokeColor(COLORS.border).lineWidth(1)
           .moveTo(50, doc.page.height - 50)
           .lineTo(550, doc.page.height - 50)
           .stroke();
        
        doc.fillColor('#999999').fontSize(8)
           .text('Generated by System', 50, doc.page.height - 40, { align: 'left' })
           .text(`Page ${i + 1} of ${pages.count}`, 50, doc.page.height - 40, { align: 'right' });
    }
};

const drawTableRow = (doc, y, columns, isHeader = false, isStriped = false) => {
    const height = 20;
    
    // Draw Background for Header or Striped Row
    if (isHeader) {
        doc.rect(50, y - 5, 500, height + 5).fill(COLORS.primary);
        doc.fillColor('#FFFFFF').font(FONTS.bold).fontSize(10);
    } else {
        if (isStriped) doc.rect(50, y - 5, 500, height + 5).fill(COLORS.grayLight);
        doc.fillColor(COLORS.text).font(FONTS.regular).fontSize(10);
    }

    // Draw Columns
    columns.forEach(col => {
        doc.text(col.text, col.x, y, { width: col.width, align: col.align || 'left' });
    });
    
    // Reset Fill Color
    doc.fillColor(COLORS.text);
};


/**
 * Generates a sales report PDF.
 */
export function generateSalesReport(user, transactions, periodTitle) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            let currentY = drawHeader(doc, user, 'Sales Report', periodTitle);

            // Table Column Config
            const colDate = { x: 60, width: 80, align: 'left' };
            const colDesc = { x: 150, width: 250, align: 'left' };
            const colAmt = { x: 410, width: 130, align: 'right' };

            // Header
            drawTableRow(doc, currentY, [
                { text: 'DATE', ...colDate },
                { text: 'DESCRIPTION', ...colDesc },
                { text: 'AMOUNT', ...colAmt }
            ], true);
            currentY += 25;

            // Rows
            let totalSales = 0;
            transactions.forEach((tx, i) => {
                // Check Page Break
                if (currentY > 750) { doc.addPage(); currentY = 50; }

                totalSales += tx.amount;
                const formattedAmount = formatCurrency(tx.amount, user.currency);
                
                drawTableRow(doc, currentY, [
                    { text: new Date(tx.date).toLocaleDateString(), ...colDate },
                    { text: tx.description, ...colDesc },
                    { text: formattedAmount, ...colAmt }
                ], false, i % 2 === 0);
                
                currentY += 20;
            });

            // Total Section
            currentY += 10;
            doc.moveTo(50, currentY).lineTo(550, currentY).strokeColor(COLORS.border).stroke();
            currentY += 10;
            
            doc.font(FONTS.bold).fontSize(12).text('Total Sales:', 300, currentY, { align: 'right', width: 100 });
            doc.fillColor(COLORS.accent).text(formatCurrency(totalSales, user.currency), 410, currentY, { align: 'right', width: 130 });

            drawFooter(doc);
            doc.end();
        } catch (error) {
            logger.error('Error generating PDF report:', error);
            reject(error);
        }
    });
}

/**
 * Generates an expense report PDF.
 */
export function generateExpenseReport(user, transactions, periodTitle) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            let currentY = drawHeader(doc, user, 'Expense Report', periodTitle);

            // Table Config
            const cols = [
                { id: 'date', x: 60, width: 80, label: 'DATE' },
                { id: 'cat', x: 150, width: 100, label: 'CATEGORY' },
                { id: 'desc', x: 260, width: 140, label: 'DESCRIPTION' },
                { id: 'amt', x: 410, width: 130, label: 'AMOUNT', align: 'right' }
            ];

            // Header
            drawTableRow(doc, currentY, cols.map(c => ({ text: c.label, x: c.x, width: c.width, align: c.align })), true);
            currentY += 25;

            // Rows
            let totalExpenses = 0;
            transactions.forEach((tx, i) => {
                if (currentY > 750) { doc.addPage(); currentY = 50; }
                
                totalExpenses += tx.amount;
                
                drawTableRow(doc, currentY, [
                    { text: new Date(tx.date).toLocaleDateString(), ...cols[0] },
                    { text: tx.category, ...cols[1] },
                    { text: tx.description, ...cols[2] },
                    { text: formatCurrency(tx.amount, user.currency), ...cols[3] }
                ], false, i % 2 === 0);
                currentY += 20;
            });

            // Total
            currentY += 10;
            doc.moveTo(50, currentY).lineTo(550, currentY).strokeColor(COLORS.border).stroke();
            currentY += 10;
            doc.font(FONTS.bold).fontSize(12).fillColor(COLORS.text).text('Total Expenses:', 250, currentY, { align: 'right', width: 150 });
            doc.fillColor('red').text(formatCurrency(totalExpenses, user.currency), 410, currentY, { align: 'right', width: 130 });

            drawFooter(doc);
            doc.end();

        } catch (error) {
            logger.error('Error generating Expense PDF report:', error);
            reject(error);
        }
    });
}

/**
 * Generates an inventory report PDF.
 */
export function generateInventoryReport(user, products) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 40, size: 'A4', bufferPages: true });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            let currentY = drawHeader(doc, user, 'Inventory Report', `As of ${new Date().toLocaleDateString()}`);

            // Columns
            const colName = { x: 50, width: 180 };
            const colQty = { x: 240, width: 50, align: 'center' };
            const colCost = { x: 300, width: 70, align: 'right' };
            const colSell = { x: 380, width: 70, align: 'right' };
            const colVal = { x: 460, width: 90, align: 'right' };

            // Header
            drawTableRow(doc, currentY, [
                { text: 'PRODUCT', ...colName },
                { text: 'QTY', ...colQty },
                { text: 'COST', ...colCost },
                { text: 'PRICE', ...colSell },
                { text: 'VALUE', ...colVal },
            ], true);
            currentY += 25;

            let totalValue = 0;

            products.forEach((p, i) => {
                if (currentY > 750) { doc.addPage(); currentY = 50; }
                
                const itemValue = p.quantity * p.costPrice;
                totalValue += itemValue;
                
                drawTableRow(doc, currentY, [
                    { text: p.productName, ...colName },
                    { text: p.quantity.toString(), ...colQty },
                    { text: new Intl.NumberFormat('en-US').format(p.costPrice), ...colCost },
                    { text: new Intl.NumberFormat('en-US').format(p.sellingPrice), ...colSell },
                    { text: new Intl.NumberFormat('en-US').format(itemValue), ...colVal },
                ], false, i % 2 === 0);
                currentY += 20;
            });

            // Footer Summary
            currentY += 15;
            doc.rect(300, currentY - 5, 250, 30).fill(COLORS.grayLight);
            doc.fillColor(COLORS.primary).font(FONTS.bold).fontSize(12)
               .text('Total Inventory Value:', 310, currentY, { width: 140, align: 'right' });
            doc.fillColor(COLORS.accent).text(formatCurrency(totalValue, user.currency), 460, currentY, { width: 90, align: 'right' });

            drawFooter(doc);
            doc.end();

        } catch (error) {
            logger.error('Error generating Inventory PDF report:', error);
            reject(error);
        }
    });
}

/**
 * Generates a Profit & Loss (P&L) report PDF.
 */
export function generatePnLReport(user, pnlData, periodTitle) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            let y = drawHeader(doc, user, 'Profit & Loss', periodTitle);
            const rightX = 400;
            const widthAmt = 140;

            const drawSection = (title, amount, isNegative = false) => {
                doc.font(FONTS.bold).fontSize(12).fillColor(COLORS.primary).text(title, 60, y);
                doc.font(FONTS.regular).fillColor(isNegative ? 'red' : COLORS.text)
                   .text(formatCurrency(amount, user.currency), rightX, y, { align: 'right', width: widthAmt });
                y += 25;
            };

            const drawSubItem = (label, amount) => {
                doc.font(FONTS.regular).fontSize(10).fillColor(COLORS.text).text(label, 80, y);
                doc.text(formatCurrency(amount, user.currency), rightX, y, { align: 'right', width: widthAmt });
                y += 20;
            };

            const drawLine = () => {
                doc.moveTo(60, y).lineTo(540, y).strokeColor(COLORS.border).stroke();
                y += 15;
            }

            // Revenue
            drawSection('Revenue', pnlData.totalSales);
            drawLine();

            // COGS
            drawSection('Cost of Goods Sold', pnlData.totalCogs);
            drawLine();

            // Gross Profit
            doc.rect(50, y - 5, 500, 30).fill('#e8f4fc'); // Light blue bg
            doc.fillColor(COLORS.primary).font(FONTS.bold).fontSize(14).text('Gross Profit', 60, y + 5);
            doc.text(formatCurrency(pnlData.grossProfit, user.currency), rightX, y + 5, { align: 'right', width: widthAmt });
            y += 40;

            // Expenses
            doc.font(FONTS.bold).fontSize(12).fillColor(COLORS.primary).text('Operating Expenses', 60, y);
            y += 20;
            pnlData.topExpenses.forEach(exp => {
                drawSubItem(exp._id, exp.total);
            });
            y += 10;
            
            // Total Expenses
            doc.moveTo(350, y).lineTo(540, y).stroke();
            y += 10;
            doc.font(FONTS.bold).text('Total Expenses', 250, y, { align: 'right', width: 140 });
            doc.text(formatCurrency(pnlData.totalExpenses, user.currency), rightX, y, { align: 'right', width: widthAmt });
            y += 30;

            // Net Profit
            const isLoss = pnlData.netProfit < 0;
            const bg = isLoss ? '#fce8e8' : '#e8fce8'; // Light red or green
            doc.rect(50, y - 10, 500, 40).fill(bg);
            
            doc.fillColor(COLORS.primary).fontSize(16).font(FONTS.bold).text('Net Profit / (Loss)', 60, y);
            doc.fillColor(isLoss ? 'red' : 'green')
               .text(formatCurrency(pnlData.netProfit, user.currency), rightX, y, { align: 'right', width: widthAmt });

            drawFooter(doc);
            doc.end();

        } catch (error) {
            logger.error('Error generating P&L PDF report:', error);
            reject(error);
        }
    });
}

/**
 * Generates a professional Invoice.
 */
export function generateInvoice(user, transaction, customer) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // --- INVOICE HEADER ---
            doc.rect(0, 0, 600, 120).fill(COLORS.primary); // Top Banner
            
            // Business Info (White text on blue)
            doc.fillColor('#FFFFFF').fontSize(24).font(FONTS.bold)
               .text(user.businessName, 50, 40);
            doc.fontSize(10).font(FONTS.regular).text(user.email || '', 50, 70);
            
            // Invoice Label (Right side)
            doc.fontSize(30).text('INVOICE', 400, 40, { align: 'right' });
            doc.fontSize(10).text(`#${transaction._id.toString().slice(-8).toUpperCase()}`, 400, 80, { align: 'right' });

            let y = 150;

            // --- BILL TO INFO ---
            doc.fillColor(COLORS.text);
            doc.fontSize(10).font(FONTS.bold).text('BILL TO:', 50, y);
            doc.font(FONTS.regular).text(customer.customerName, 50, y + 15);
            // Add customer address/phone if available
            
            // Date Info
            doc.font(FONTS.bold).text('DATE:', 400, y, { align: 'right', width: 50 });
            doc.font(FONTS.regular).text(new Date(transaction.date).toLocaleDateString(), 460, y, { align: 'right', width: 80 });
            
            y += 60;

            // --- TABLE ---
            const colItem = { x: 50, width: 250 };
            const colQty = { x: 310, width: 50, align: 'center' };
            const colPrice = { x: 370, width: 80, align: 'right' };
            const colTotal = { x: 460, width: 80, align: 'right' };

            // Header
            drawTableRow(doc, y, [
                { text: 'ITEM DESCRIPTION', ...colItem },
                { text: 'QTY', ...colQty },
                { text: 'PRICE', ...colPrice },
                { text: 'TOTAL', ...colTotal },
            ], true);
            y += 30;

            // Items
            transaction.items.forEach((item, i) => {
                const itemTotal = item.quantity * item.pricePerUnit;
                drawTableRow(doc, y, [
                    { text: item.productName, ...colItem },
                    { text: item.quantity.toString(), ...colQty },
                    { text: formatCurrency(item.pricePerUnit, user.currency), ...colPrice },
                    { text: formatCurrency(itemTotal, user.currency), ...colTotal },
                ], false, i % 2 === 0);
                y += 25;
            });

            // --- TOTALS SECTION ---
            y += 20;
            const totalBoxX = 350;
            const totalBoxWidth = 190;
            
            // Line
            doc.moveTo(totalBoxX, y).lineTo(550, y).strokeColor(COLORS.accent).lineWidth(2).stroke();
            y += 15;

            // Grand Total
            doc.fillColor(COLORS.primary).font(FONTS.bold).fontSize(14)
               .text('Grand Total', totalBoxX, y, { width: 80, align: 'left' });
            
            doc.fillColor(COLORS.accent).fontSize(14)
               .text(formatCurrency(transaction.amount, user.currency), 440, y, { width: 100, align: 'right' });

            // --- FOOTER ---
            const pageHeight = doc.page.height;
            doc.rect(0, pageHeight - 80, 600, 80).fill('#f9f9f9'); // Light footer bg
            
            doc.fillColor(COLORS.text).fontSize(10).font(FONTS.italic)
               .text('Thank you for your business!', 50, pageHeight - 50, { align: 'center', width: 500 });

            doc.end();

        } catch (error) {
            logger.error('Error generating invoice PDF:', error);
            reject(error);
        }
    });
}
