export const USER_STATES = {
  // A brand new user, has sent their first message
  NEW_USER: 'NEW_USER',
  
  // Onboarding States
  ONBOARDING_AWAIT_BUSINESS_AND_EMAIL: 'ONBOARDING_AWAIT_BUSINESS_AND_EMAIL',
  ONBOARDING_AWAIT_OTP: 'ONBOARDING_AWAIT_OTP',
  ONBOARDING_AWAIT_CURRENCY: 'ONBOARDING_AWAIT_CURRENCY',

  // Core State
  IDLE: 'IDLE',

  // Task-specific states
  LOGGING_SALE: 'LOGGING_SALE',
  AWAITING_SALE_TYPE_CONFIRMATION: 'AWAITING_SALE_TYPE_CONFIRMATION', 
  LOGGING_MULTI_ITEM_SALE: 'LOGGING_MULTI_ITEM_SALE', 
  LOGGING_EXPENSE: 'LOGGING_EXPENSE',
  ADDING_PRODUCT: 'ADDING_PRODUCT',
  LOGGING_CUSTOMER_PAYMENT: 'LOGGING_CUSTOMER_PAYMENT',
  
  ADDING_BANK_ACCOUNT: 'ADDING_BANK_ACCOUNT', 
  AWAITING_BANK_MENU_SELECTION: 'AWAITING_BANK_MENU_SELECTION',

  AWAITING_BANK_SELECTION_SALE: 'AWAITING_BANK_SELECTION_SALE',
  AWAITING_BANK_SELECTION_EXPENSE: 'AWAITING_BANK_SELECTION_EXPENSE',
  AWAITING_BANK_SELECTION_PURCHASE: 'AWAITING_BANK_SELECTION_PURCHASE', 
  AWAITING_BANK_SELECTION_CUST_PAYMENT: 'AWAITING_BANK_SELECTION_CUST_PAYMENT', 
  AWAITING_BANK_SELECTION_BULK: 'AWAITING_BANK_SELECTION_BULK', 

  AWAITING_BULK_PRODUCT_CONFIRMATION: 'AWAITING_BULK_PRODUCT_CONFIRMATION',
  AWAITING_INVOICE_CONFIRMATION: 'AWAITING_INVOICE_CONFIRMATION',

  // Reconciliation States
  AWAITING_TRANSACTION_SELECTION: 'AWAITING_TRANSACTION_SELECTION',
  AWAITING_RECONCILE_ACTION: 'AWAITING_RECONCILE_ACTION',
  AWAITING_EDIT_FIELD_SELECTION: 'AWAITING_EDIT_FIELD_SELECTION',
  AWAITING_EDIT_VALUE: 'AWAITING_EDIT_VALUE',
  AWAITING_DELETE_CONFIRMATION: 'AWAITING_DELETE_CONFIRMATION',

  AWAITING_REPORT_TYPE_SELECTION: 'AWAITING_REPORT_TYPE_SELECTION',
  
  // [NEW] Subscription States
  AWAITING_PAYMENT_METHOD_SELECTION: 'AWAITING_PAYMENT_METHOD_SELECTION'
};

export const INTENTS = {
    LOG_SALE: 'LOG_SALE',
    LOG_EXPENSE: 'LOG_EXPENSE',
    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_MULTIPLE_PRODUCTS: 'ADD_MULTIPLE_PRODUCTS',
    ADD_PRODUCTS_FROM_LIST: 'ADD_PRODUCTS_FROM_LIST',
    CHECK_STOCK: 'CHECK_STOCK',
    GET_FINANCIAL_SUMMARY: 'GET_FINANCIAL_SUMMARY',
    GENERATE_REPORT: 'GENERATE_REPORT',
    
    LOG_CUSTOMER_PAYMENT: 'LOG_CUSTOMER_PAYMENT',
    ADD_BANK_ACCOUNT: 'ADD_BANK_ACCOUNT', 
    CHECK_BANK_BALANCE: 'CHECK_BANK_BALANCE',
    
    RECONCILE_TRANSACTION: 'RECONCILE_TRANSACTION',
    GET_FINANCIAL_INSIGHT: 'GET_FINANCIAL_INSIGHT',
    GET_CUSTOMER_BALANCES: 'GET_CUSTOMER_BALANCES',
    SHOW_MAIN_MENU: 'SHOW_MAIN_MENU',
    GENERAL_CONVERSATION: 'GENERAL_CONVERSATION',
    
    MANAGE_TEAM: 'MANAGE_TEAM',
    EXPORT_DATA: 'EXPORT_DATA',
    
    // [NEW] Subscription Intents
    CHECK_SUBSCRIPTION: 'CHECK_SUBSCRIPTION',
    UPGRADE_SUBSCRIPTION: 'UPGRADE_SUBSCRIPTION'
};

export const EXPENSE_CATEGORIES = [
    "Transportation",       
    "Utilities & Internet", 
    "Rent & Office",        
    "Salaries & Wages",     
    "Marketing & Ads",      
    "Meals & Entertainment",
    "Supplies & Packaging", 
    "Restocking (Inventory)", 
    "Miscellaneous"         
];
