export const USER_STATES = {
  // A brand new user, has sent their first message
  NEW_USER: 'NEW_USER',
  
  // Onboarding States
  ONBOARDING_AWAIT_BUSINESS_AND_EMAIL: 'ONBOARDING_AWAIT_BUSINESS_AND_EMAIL',
  ONBOARDING_AWAIT_OTP: 'ONBOARDING_AWAIT_OTP',
  ONBOARDING_AWAIT_CURRENCY: 'ONBOARDING_AWAIT_CURRENCY',

  // Core State
  IDLE: 'IDLE',

  // Task-specific states
  LOGGING_SALE: 'LOGGING_SALE',
  LOGGING_EXPENSE: 'LOGGING_EXPENSE',
  ADDING_PRODUCT: 'ADDING_PRODUCT',
  LOGGING_CUSTOMER_PAYMENT: 'LOGGING_CUSTOMER_PAYMENT',
  ADDING_BANK_ACCOUNT: 'ADDING_BANK_ACCOUNT',
  AWAITING_BULK_PRODUCT_CONFIRMATION: 'AWAITING_BULK_PRODUCT_CONFIRMATION',
  AWAITING_INVOICE_CONFIRMATION: 'AWAITING_INVOICE_CONFIRMATION',

};

export const INTENTS = {
    LOG_SALE: 'LOG_SALE',
    LOG_EXPENSE: 'LOG_EXPENSE',
    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_MULTIPLE_PRODUCTS: 'ADD_MULTIPLE_PRODUCTS',
    CHECK_STOCK: 'CHECK_STOCK',
    GET_FINANCIAL_SUMMARY: 'GET_FINANCIAL_SUMMARY',
    GENERATE_REPORT: 'GENERATE_REPORT',
    LOG_CUSTOMER_PAYMENT: 'LOG_CUSTOMER_PAYMENT',
    ADD_BANK_ACCOUNT: 'ADD_BANK_ACCOUNT',
};
